import os
import time
import uuid
from typing import AsyncGenerator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage

from src.schemas import ChatCompletionRequest, ChatCompletionChunk, ChoiceChunk, Delta, Message
from src.graph import app as workflow_app

app = FastAPI(
    title="Godot Local RAG Agent API",
    description="OpenAI API Compatible",
    version="1.0.0"
)

CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if origin.strip()
]

if CORS_ALLOWED_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=CORS_ALLOWED_ORIGINS,
        allow_credentials=False,  # no cookies/auth are used
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["Content-Type", "Authorization"],
    )

def convert_messages(messages: list[Message]) -> list[HumanMessage | AIMessage | SystemMessage]:
    """Convert messages from the OpenAI format to LangChain messages."""
    lc_messages = []
    for msg in messages:
        if msg.role == "user":
            lc_messages.append(HumanMessage(content=msg.content))
        elif msg.role == "assistant":
            lc_messages.append(AIMessage(content=msg.content))
        elif msg.role == "system":
            lc_messages.append(SystemMessage(content=msg.content))
    return lc_messages

async def event_generator(request: ChatCompletionRequest) -> AsyncGenerator[str, None]:
    """Generate OpenAI-compatible Server-Sent Events (SSE)."""
    req_id = f"chatcmpl-{uuid.uuid4().hex}"
    created = int(time.time())
    
    # Prepare the agent's initial state.
    initial_state = {"messages": convert_messages(request.messages)}
    
    # Capture token-level streaming events from the graph.
    async for event in workflow_app.astream_events(initial_state):
        # Only handle tokens generated by the final node ("generate_node").
        if event["event"] == "on_chat_model_stream" and event.get("metadata", {}).get("langgraph_node") == "generate_node":
            token = event["data"]["chunk"].content
            if token:
                chunk = ChatCompletionChunk(
                    id=req_id,
                    created=created,
                    model=request.model,
                    choices=[
                        ChoiceChunk(
                            index=0,
                            delta=Delta(content=token)
                        )
                    ]
                )
                yield f"data: {chunk.model_dump_json(exclude_none=True)}\n\n"
    
    # Send the end-of-stream marker specified by OpenAI.
    yield "data: [DONE]\n\n"

@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """Main endpoint for requests from Continue.dev."""
    if request.stream:
        return StreamingResponse(
            event_generator(request), 
            media_type="text/event-stream"
        )
    else:
        # This endpoint currently supports streaming requests only.
        return {"error": "Please enable 'stream: true' in your code agent configuration."}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("src.main:app", host="0.0.0.0", port=8000, reload=True)
